export default 
  [
    "querySelector",
    "getElementId",
    "parentNode",
    "parentSibling",
    "childNodes",
    "firstChild",
    "lastChild",
    "previousSibling",
    "nextSibling",
    "nodeType",
    "nodeName",
    "textContent",
    "innerHTML",
    "insertAdjacentHTML",
    "createElement",
    "appendChild",
    "insertBefore",
    "cloneNode",
    "replaceChild",
    "removeChild",
    "getAttribute",
    "dataset",
    "className",
    "classList",
    "getComputedStyle"
  ]

